name: ci

on:
  push:
    branches:
      - master

jobs:
  buildx:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
         with:
          platforms: 'arm64,arm'
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       - name: cd
         run: |
          cd 1/scratch
          docker build --no-cache -t  rmq-default-credential-updater:v1 .
          docker save -o rmq-default-credential-updater.tar rmq-default-credential-updater:v1 
          cd ../
       - name: Create Release
         if: ${{ steps.response_info_1.outputs.run_project_b_build == 'true' }}
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: v0.0.1
           release_name: Release v0.0.1
           body_path: 1/scratch/rmq-default-credential-updater.tar
           draft: false
           prerelease: false
